app.py
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from flask import g, Flask, flash, redirect, render_template, url_for
from flask_caching import Cache
from flask_login import LoginManager, current_user
from flask_mail import Mail

from config import Config
from classes.user import User

login_manager = LoginManager()
cache = Cache()
mail = Mail()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    login_manager.init_app(app)
    cache.init_app(app)
    mail.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.get(user_id)

    @app.teardown_appcontext
    def close_connection(exception):
        db = getattr(g, '_database', None)
        if db is not None:
            db.close()

    @app.errorhandler(401)
    def unauthorized(e):
        flash('You need to be logged in to view this page.', 'warning')
        return redirect(url_for('auth.login'))
    
    app.register_error_handler(401, unauthorized)

    @app.before_request
    def load_logged_in_user():
        g.user = current_user
    
    @app.route('/')
    def index():
        return redirect(url_for('auth.login'))
    
    from home.routes import Home
    from auth.routes import Auth
    from mycalendar.routes import MyCalendar
    from messaging.routes import Messaging
    from search.routes import Search

    app.register_blueprint(Home, url_prefix='/home')
    app.register_blueprint(Auth, url_prefix='/auth')
    app.register_blueprint(Messaging, url_prefix='/messaging')
    app.register_blueprint(Search, url_prefix='/search')
    app.register_blueprint(MyCalendar, url_prefix='/myCalendar')



    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

home/routes.py
import json
import os, sys
from flask import render_template, Blueprint, request
from flask_login import login_required

from config import Config
from myutils import open_json




Home = Blueprint('home', __name__, template_folder='templates', static_folder='static')

@Home.route("/home", methods=['GET','POST'])
@login_required
def home():
    
    return render_template('home.html', title='Home')

messaging/routes.py
import json
import os, sys
from flask import render_template, Blueprint, request
from flask_login import login_required

from config import Config
from myutils import open_json




Messaging = Blueprint('messaging', __name__, template_folder='templates', static_folder='static')

@Messaging.route("/messaging", methods=['GET','POST'])
@login_required
def messaging():
    
    return render_template('messaging.html', title='Messaging')

mycalendar/routes.py
import json
import os, sys
from flask import render_template, Blueprint, request
from flask_login import login_required

from config import Config
from myutils import open_json



MyCalendar = Blueprint('calendar', __name__, template_folder='templates', static_folder='static')

@MyCalendar.route("/calendar", methods=['GET','POST'])
@login_required
def calendar():
    
    return render_template('calendar.html', title='Calendar')

search/routes.py
import json
import os, sys
from flask import render_template, Blueprint, request
from flask_login import login_required

from config import Config
from myutils import open_json




Search = Blueprint('search', __name__, template_folder='templates', static_folder='static')

@Search.route("/search", methods=['GET','POST'])
@login_required
def search():
    
    return render_template('search.html', title='Search')

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rentify</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cards.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/containers.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}">
</head>

<body>
    <div class="background">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flashes" id="flash-message">
                        {% for category, message in messages %}
                            <div class="flash-message {{ category }}">{{ message }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <div class="nav-bar">
        <div class="nav-bar-icon">
            <a href="{{ url_for('home.home') }}">
                <img src="{{ url_for('static', filename='imgs/icons/home.png') }}" alt="Home">
            </a>
                <div class="nav-bar-text">Home</div>
        </div>
        <div class="nav-bar-icon">
            <a href="{{ url_for('messaging.messaging') }}">
                <img src="{{ url_for('static', filename='imgs/icons/messaging.png') }}" alt="Pitch">
            </a>
            <div class="nav-bar-text">Talk with people</div>
        </div>
        <div class="nav-bar-icon">
            <a href="{{ url_for('search.search') }}">
                <img src="{{ url_for('static', filename='imgs/icons/search.png') }}" alt="Pitch">
            </a>
            <div class="nav-bar-text">Search for items</div>
        </div>
        <div class="nav-bar-icon">
            <a href="{{ url_for('calendar.calendar') }}">
                <img src="{{ url_for('static', filename='imgs/icons/calendar.png') }}" alt="Pitch">
            </a>
            <div class="nav-bar-text">View your items</div>
        </div>


        <div class="nav-bar-icon">
            <a href="{{ url_for('auth.logout') }}">
                <img src="{{ url_for('static', filename='imgs/icons/logout.png') }}" alt="Logout">
            </a>
            <div class="nav-bar-text">Logout</div>
        </div>
        
        <div class="logo" style="margin-top: auto; margin-bottom: 3rem; text-align: center; margin-right: 0.5rem;">
            <img src="{{ url_for('static', filename='imgs/logo.png') }}" alt="Rentify Logo" style="height: 6vh;">
        </div>
    </div>
</body>
</html>